[package]
name = "eugene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "eugene"
version = "0.1.0"
edition = "2021"
features = ["extension-module"]

[dependencies]
bit-vec = "*"
svg = "*"
rand = "*"
num = "*"
pathfinding = "*"
itertools = "0.11.0"
pyo3 = "0.20.2"
